const EVENTS = Object.freeze({
  CONNECTED: "socket:connected",
  ERROR: "socket:error",
  PRESENCE_SYNC: "presence:sync",
  PRESENCE_USER_ONLINE: "presence:user_online",
  PRESENCE_USER_OFFLINE: "presence:user_offline",
  NOTIFICATION_CREATED: "notification:created",
  NOTIFICATION_READ: "notification:read",
  NOTIFICATIONS_READ_ALL: "notification:read_all",
  CONVERSATION_JOIN: "conversation:join",
  CONVERSATION_LEAVE: "conversation:leave",
  CONVERSATION_LIST: "conversation:list",
  CONVERSATION_UPDATED: "conversation:updated",
  MESSAGE_SEND: "message:send",
  MESSAGE_CREATED: "message:created",
  MESSAGE_SEEN: "message:seen",
  TYPING_START: "typing:start",
  TYPING_STOP: "typing:stop",
  BOOKING_CREATED: "booking:created",
  BOOKING_UPDATED: "booking:updated",
  LISTING_CREATED: "listing:created",
  LISTING_UPDATED: "listing:updated",
  LISTING_DELETED: "listing:deleted",
});

module.exports = EVENTS;
